In [2]:
import numpy as np

## 1. 값이 10~49인 numpy array를 만드세요

In [35]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 2. z를 반전하세요.

In [36]:
z = np.flip(z)
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## 3. 반전시킨 z 매트릭스를 10 x 4 매트릭스로 바꾸세요.

In [13]:
z = z.reshape(10, 4)
print(z)

[[49 48 47 46]
 [45 44 43 42]
 [41 40 39 38]
 [37 36 35 34]
 [33 32 31 30]
 [29 28 27 26]
 [25 24 23 22]
 [21 20 19 18]
 [17 16 15 14]
 [13 12 11 10]]


## 4. x에서 0이 아닌 요소의 색인을 찾아보세요.

In [14]:
x = np.array([5,6,8,0,1,0,7])
nz_idx = np.where(x != 0)
print(nz_idx)

(array([0, 1, 2, 4, 6], dtype=int64),)


## nan 값 이해하기

In [15]:
print(np.nan == np.nan)
print(np.isnan(np.nan))

import math
print(0.3 == 3 * 0.1)
print(math.isclose(0.1 + 0.2, 0.3))

False
True
False
True


## 5. 12 x 12 매트릭스를 만들어 바둑판 패턴으로 0과 1을 채우세요

In [43]:
x = np.zeros((12, 12))
print(len(x))

12


In [45]:
x = np.zeros((12, 12))
print(x, end='\n\n')
###############
# 슬라이싱을 사용하세요
for i in range(0, len(x)):
    if i%2 == 0: 
        x[i:i+1, 1::2] = 1
    if i%2 == 1:
        x[i:i+1, ::2] = 1
###############
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]


## 6. np.tile 을 이용해서 동일한 바둑판 패턴을 만들어보세요

In [63]:
p = np.array([[0,1], [1,0]])
x = np.tile(p, [6,6])
print(x)

[[0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]]


## 7. 1차원 배열이 x에서 값이 5~10인 요소를 0으로 바꾸세요

In [64]:
x = np.array([2,5,3,8,3,34,23,7,10])
print(x)
##################
# 필터링을 사용하세요.
x[(x>=5) & (x<=10)] = 0

##################
print(x)

[ 2  5  3  8  3 34 23  7 10]
[ 2  0  3  0  3 34 23  0  0]


## 8. 0에서 100 사이의 값으로 크기가 10인 1차원 array를 만드세요

In [65]:
x = np.linspace(0,100,10)
print(x)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


## 9. np.allclose() 함수를 사용하여 2개의 array가 같은지를 확인해보세요

In [66]:
A = np.array([1e10,1e-8])
B = np.array([1.00001e10,1e-9])

equal = np.allclose(A, B)
print(equal)

True


## 10. 데카르트 좌표를 나타내는 랜덤 8 x 2 행렬을 고려하여 극좌표로 변환해보세요.

In [82]:
coord = np.random.random((10,2))

x, y = coord[:,0], coord[:,1]

r = np.sqrt(x**2+y**2)
theta = np.arctan2(y,x)

ploar_coord = np.concatenate([r[:,np.newaxis], theta[:,np.newaxis]],axis=1)
print(ploar_coord)

[[1.04714358 1.05379683]
 [0.07044919 1.53900654]
 [0.21385615 0.25540594]
 [1.14155543 1.03665906]
 [0.45257177 0.38372869]
 [0.86682085 1.33376898]
 [0.83847266 1.13315604]
 [0.61738211 0.69442004]
 [0.24419683 0.68076121]
 [0.72564295 1.30047494]]


In [67]:
coord = np.random.random((10,2))

In [68]:
coord

array([[0.42234443, 0.19645666],
       [0.07062385, 0.74094028],
       [0.89043528, 0.44038064],
       [0.89076179, 0.54057745],
       [0.36499811, 0.38631646],
       [0.82436777, 0.88795435],
       [0.18981513, 0.16397069],
       [0.0769206 , 0.23989253],
       [0.22326398, 0.14496746],
       [0.99715565, 0.2063522 ]])

In [69]:
x, y = coord[:,0], coord[:,1]
print(x, end='\n\n')
print(y)

[0.42234443 0.07062385 0.89043528 0.89076179 0.36499811 0.82436777
 0.18981513 0.0769206  0.22326398 0.99715565]

[0.19645666 0.74094028 0.44038064 0.54057745 0.38631646 0.88795435
 0.16397069 0.23989253 0.14496746 0.2063522 ]


In [ ]:
# z = x + 1j * y 
# r = np.abs(z)
# theta = np.angle(z)